name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *" # 每天零点自动更新
  workflow_dispatch: # 支持手动触发
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.5.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./snake.svg?color_snake=4ECDC4&palette=github-light
            ./snake-dark.svg?color_snake=4ECDC4&palette=github-dark
      - name: 提交生成的蛇图
        uses: EndBug/add-and-commit@v9
        with:
          message: "自动更新贪吃蛇贡献图"
